### PR TITLE
Added EventEmitter generic possibility

### LINKED ISSUE #105: Add generic types for EventEmitter
Like: `new EventEmitter<OpenEvent>()`.

### PR DESCRIPTION
**Pull request by endway**
Fixes #105

### CODE REVIEW

**Review by Krakabek — APPROVED** [review]
VERY IMPORTANT UPDATE, THANKS @endway!!!!

**Review by Krakabek — APPROVED** [review]

**Review by arodik — APPROVED** [review]

**Comment by arodik** [comment]
Great 🔥, but unfortunately I don't have the right to merge the PR.
@melya plz help :)))

**Comment by melya** [comment]
@arodik try again)

**Comment by arodik** [comment]
Still can't :)
"At least 1 approving review is required by reviewers with write access"

**Comment by arodik** [comment]
Would be great if you grant the write access for @endway

**Comment by melya** [comment]
Write access was always enabled for all the Frontend team ;)

**Pull request merged**
